version: '3.8'

services:
  mongodb:
    build:
      dockerfile: Dockerfile
    image: mongocustom:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  #initialize mongo replicaset from another container:
  mongoinit:
    build:
      dockerfile: Dockerfile
    image: mongocustom:latest
    hostname: mongodbinit
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --username admin --password adminpassword --authenticationDatabase admin --eval
      '
      rs.initiate();
      '
  redis-stack:
    image: redis/redis-stack:7.0.6-RC2
    #    volumes:
    #      - redis-stack-data:/bitnami/redis/data
    ports:
      - "8001:8001"
      - "6379:6379"

volumes:
  redis-stack-data:
    driver: local

